# Generated by Django 5.0 on 2024-01-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=1000)),
                ("lname", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=1000)),
                ("password", models.CharField(max_length=1000)),
            ],
        ),
    ]
